### ISSUE TITLE
Avoid from mymodule.mymodule import method

### ISSUE THREAD

**Issue by phndiaye** [upfluence/intranet-api#11]
You can write code in the `__init__.py` instead of creating a file that have the same name as the module.

For example, in endpoints module, you can move the content of `endpoints/endpoints.py` in `endpoints/__init__.py`. Then in `app.py` you can import using `from intranet.endpoints import register_blueprint` instead of `from intranet.endpoints.endpoints import ...`. It can be really confusing as the project grows up

**Comment by aguadoenzo** [comment]
Indeed, nice catch ! :+1:
